---
- name: Check if variables are set
  fail:
    msg: "dhcpcd_interface and dhcpcd_ip_address needs to be defined"
  when:
    - (dhcpcd_interface is not defined) or (dhcpcd_ip_address is not defined)

- name: Install dhcpcd
  apt:
    name: dhcpcd5
    state: present

- name: Check dhcpcd service is started and enabled
  service:
    name: dhcpcd
    state: started
    enabled: true

- name: Apply dhcpcd.conf template
  template:
    src: dhcpcd.conf.j2
    dest: "{{ dhcpcd_conf_location }}"
    mode: "0644"
  notify: reboot system

- name: Force handler to be executed
  meta: flush_handlers
...