---

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: false

- name: Install dhcpcd
  apt:
    name: dhcpcd5
    state: present

- name: Check dhcpcd service is started and enabled
  service:
    name: dhcpcd
    state: started
    enabled: true

- name: Apply dhcpcd.conf template
  template:
    src: dhcpcd.conf.j2
    dest: "{{ dhcpcd_conf_location }}"
    mode: "0644"
  notify: reboot system

- name: Force handler to be executed
  meta: flush_handlers

...
