---
- name: Converge
  hosts: all
  gather_facts: yes
  tasks:
    - name: Include ansible-role-dhcpcd
      include_role:
        name: ansible-role-dhcpcd
      vars:
        reboot: false
        dhcpcd_interface: "eth0"
        dhcpcd_ip_address: "10.0.0.1"
...
